### ISSUE TITLE
obj2.js

### ISSUE THREAD

**Issue by MrGolf2022** [Sprite23/64309010004_Chusanapak#1]
![สกรีนช็อต 2022-11-24 202322](https://user-images.githubusercontent.com/116155726/203794847-17f86051-7f2b-4980-a747-fb45955fed05.png)

ลองดูตรงคำนวณภาษีอีกทีนะ ♥️

**Comment by Sprite23** [comment]
แก้ไขเรียบร้อบครับผม
![image](https://user-images.githubusercontent.com/74517766/203825992-bda2695d-f6a0-4c32-b018-bf7bdf6cba72.png)
